config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#top'

  get 'about', to: 'pages#about'

  resources :plannings, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :training

  validates :count, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :num, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0}
  validates :set, presence: true
end

app/models/planning.rb
class Planning < ApplicationRecord
  # validates :allowed_time, allowed_blank: false, numericality: {only_integer: true}, length: { in: 1..3 }
end

app/models/training.rb
class Training < ApplicationRecord
  has_many :menus

  validates :name, presence: true, length: { maximum: 50 }
  validates :part, presence: true, inclusion: { in: ['脚', '胸', '肩', '背中', '腹', '腕' ]}
  validates :point, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :basis, presence: true, numericality: { greater_than_or_equal: 0 }
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/plannings_controller.rb
class PlanningsController < ApplicationController
  require 'securerandom'

  def index
    menu_latest = Menu.last
    set_latest = menu_latest.set
    @menus = Menu.where(set: set_latest).order(num: :asc)
  end

  def new
    @planning = Planning.new
  end

  def create
    @planning = Planning.new(planning_params)

    # メニュー生成用の変数
    todayLevel = (@planning.level * @planning.condition).ceil + @planning.adjustment
    i = 0
    @sumTime = 0

    # 同じセットメニューを識別するためのランダムな文字列を生成
    this_set = SecureRandom.alphanumeric(10)

    while @sumTime < @planning.allowed_time # 時間が許す限りメニューを追加していく
      # トレーニングを選んでくる処理
      if i % 2 == 0 # トレーニングと休憩を交互に
        training = Training.where(part: @planning.focus).sample  # 集中鍛錬部位に合致するトレーニングを1個選ぶ (後でランダム選択にする)
      else
        training = Training.where.not(part: @planning.focus).sample  # 集中鍛錬部位以外のトレーニングを1個選ぶ
      end

      # i 番目のメニューを作成する処理
      menu = Menu.new # インスタンスを作成
      menu.training_id = training.id 
      menu.count = (training.basis * todayLevel).ceil # 基礎レベルに倍率をかけて回数を算出
      menu.num = i # 何番目のメニューであるか
      menu.set = this_set
      menu.save

      time = ((training.time).to_f / 60 * menu.count).ceil # このトレーニングに要する時間を 1 分単位で算出
      @sumTime += time # 所要時間の計算に加算
      @sumTime += 1 # 休憩時間を加算 (1分)
      i += 1 # 次のメニュー生成へ
    end

    # @menus = Menu.where(set: this_set).order(num: :asc) # セット値が同じメニューを出力

    redirect_to plannings_path  # 作成したメニュー画面に遷移
    flash[:success] = "メニューを作成しました"
  end

  private
  def planning_params
    params.require(:planning).permit(:level, :condition, :adjustment, :focus, :allowed_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_errors_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="flash-message alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<%= javascript_pack_tag 'layouts/footer', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'layouts/footer', media: 'all', 'data-turbolinks-track': 'reload' %>

<footer>
  <div class="col-sm-12 footer-copyright">
    &copy; 2021 - PASOTRE by tmasuyama
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark px-4" style="background: #444444;">
    <a class="navbar-brand" href="/">PASOTRE</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="dropdown-item"><%= link_to 'About', about_path, class: 'link' %></li>
        <li class="dropdown-item"><%= link_to 'Planning', new_planning_path, class: 'link' %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PASOTRE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container mt-2">
      <%= render 'layouts/flash_messages' %>
    </div>
    <div id="wrapper">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<%= javascript_pack_tag 'pages/about', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'pages/about' %>

<div class="container text-center my-5">
  <h1>About</h1>

  <div class="row my-5">
    <div class="col-sm-6 offset-sm-3 my-4">
      <div class="text-center">
        <h2 class="my-4">1. Planning</h2>
        <p>5 つの質問に答えて<br>トレーニングメニューを生成</p>
        <%= image_pack_tag 'pages/about/plannings_new.gif' %>
      </div>
    </div>

    <div class="col-sm-6 offset-sm-3 my-4">
      <div class="text-center">
        <h2 class="my-4">2. Training</h2>
        <p>質問をもとに自動生成されたメニューで<br>順番にトレーニングするだけ！</p>
        <%= image_pack_tag 'pages/about/plannings_index.gif' %>
      </div>
    </div>

    <div class="col-sm-6 offset-sm-3 my-4">
      <div class="text-center">
        <h2 class="my-4">3. Check</h2>
        <p>初めてやるトレーニングは<br>やり方を確認しておきましょう</p>
        <%= image_pack_tag 'pages/about/plannings_tooltip.gif' %>
      </div>
    </div>

  </div>

  <h3 class="mb-3">Let's Start Training!</h3>
  <%= link_to "Training!", new_planning_path, class: "btn-training" %>
</div>

app/views/pages/top.html.erb
<%= javascript_pack_tag 'pages/top', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'pages/top' %>

<%# TOP %>
<div class="top-bg">
  <div class="container-fluid text-center p-5 text-light">
    <div class="top-title fw-bold">PASOTRE</div>
    <div class="top-description mt-3 mx-2 mb-5">
      <p>AI パーソナルトレーナーが<br>
      今日のアナタにピッタリなトレーニングメニューを作成<br>
      (ユーザ登録不要)</p>
    </div>
    <%= link_to "Training!", new_planning_path, class: "btn-training" %>
    <%= link_to "Learn more", about_path, class: "btn-about" %>
  </div>
</div>

<%# FEATURES %>
<div class="container text-center my-5 border-bottom">
  <h2 class="text-secondary mt-3 mb-5">FEATURES</h2>
  <div style="visibility: visible; animation-name: fadeInUp;"><span></span></div>
  <div class="row mb-5">
    <div class="col-lg-4 my-3">
      <div class="features-box-icon">
        <i class="fas fa-chart-line"></i>
      </div>
      <h3 class="my-4">Only for You</h3>
      <div class="text-secondary mt-1">
        <p>今の体調や気分を教えてください</p>
        <p>最適なメニューを作ります</p>
      </div>
    </div>
    <div class="col-lg-4 my-3">
      <div class="features-box-icon">
        <i class="fas fa-dumbbell"></i>
      </div>
      <h3 class="my-4">Fit Today</h3>
      <div class="text-secondary mt-1">
        <p>負荷はその日に合わせて調整します</p>
        <p>無理をする必要はありません</p>
      </div>
    </div>
    <div class="col-lg-4 my-3">
      <div class="features-box-icon">
        <i class="fas fa-robot"></i>
      </div>
      <h3 class="my-4">AI Trainer</h3>
      <div class="text-secondary mt-1">
        <p>いつでもどこでも</p>
        <p>AI トレーナーが付き添います</p>
      </div>
    </div>
  </div>
</div>

<%# HOW TO USE %>
<div class="container text-center my-5 border-bottom">
  <h2 class="text-secondary mt-3 mb-5">HOW TO USE</h2>
  <div class="row justify-content-center">
    <div class="col-md-4">
      <h4 class="my-4">1. ヒアリング</h4>
      <div class="text-secondary mt-1">
        <p>今日の気分や体調を入力</p>
      </div>
    </div>
    <div class="col-md-4">
      <h3 class="my-4">2. すぐトレーニング</h3>
      <div class="text-secondary mt-1">
        <p>自動生成メニューでトレーニング</p>
      </div>
    </div>
  </div>
  <%= link_to "Learn more", about_path, class: "btn-about my-3 mb-5" %>
  <%= link_to "Training!", new_planning_path, class: "btn-training" %>
</div>

app/views/plannings/index.html.erb
<%= javascript_pack_tag 'plannings/index', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'plannings/index' %>

<div class="container choose_box text-center my-5">
  <h1>Today's  Menu</h1>

  <div class="row my-5">
    <% @menus.each do |menu| %>
      <div id="<%= menu.num %>" class="col-md-6 offset-md-3 text-center">
        <div class="card">
          <div class="card-header bg-light">
            <h3 class="mt-4 mb-2"><%= menu.training.name %></h3>
            <span class="help-tooltip-trigger">
              <i class="far fa-question-circle"></i>
            </span>
            <div class="help-tooltip">
              <p><%= menu.training.description %></p>
            </div>
          </div>
          <div class="card-body">
            <h2 class="card-title">x <%= menu.count %></h2>
          </div>
        </div>
        <% if menu.num == @menus.length - 1 %>
          <a class="btn-last mt-4 mb-5" href="<%= new_planning_path %>">Clear!</a>
        <% else %>
          <a class="btn-next mt-4 mb-5">Done!</a>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/plannings/new.html.erb
<%= javascript_pack_tag 'plannings/new', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'plannings/new' %>

<div class="container choose_box text-center my-5">
  <h1>Let's make Training Menu !</h1>

  <%= form_with model: @planning do |f| %>

    <div class="form-group row">

      <!-- 質問1 -->
      <div id="q_01" class="question">
        <div class="offset-sm-2 col-sm-8 mt-5 mb-4">
          <h3>Q. 腕立て伏せを何回できますか？ (1/5)</h3>
        </div>
        <div class="offset-sm-2 col-sm-8 mb-2">
          <%= f.select :condition, [5, 10, 15, 20, 25, 30, 35, 40, 45, 50], class: "form-select" %> 回
        </div>
        <a class="btn-next my-5" href="#q_02">Next</a>
      </div>

      <!-- 質問2 -->
      <div id="q_02" style="display: none;">
        <div class="offset-sm-2 col-sm-8 mt-5 mb-4">
          <h3>Q. 今日の調子は？ (2/5)</h3>
        </div>
        <div class="offset-sm-2 col-sm-8 mb-2">
          <%= f.radio_button :condition, 1.4, {checked: true} %> 最高!
          <%= f.radio_button :condition, 1.2 %> 良い
          <%= f.radio_button :condition, 1.0 %> 普通
          <%= f.radio_button :condition, 0.8 %> 微妙
          <%= f.radio_button :condition, 0.6 %> 最悪...
        </div>
        <a class="btn-next my-5" href="#q_03">Next</a>
      </div>

      <!-- 質問3 -->
      <div id="q_03" style="display: none;">
        <div class="offset-sm-2 col-sm-8 mt-5 mb-4">
          <h3>Q. 負荷はどんな感じにしますか？ (3/5)</h3>
        </div>
        <div class="offset-sm-2 col-sm-8 mb-2">
          <%= f.radio_button :adjustment, 2, {checked: true} %> 強く
          <%= f.radio_button :adjustment, 1 %> 少し強く
          <%= f.radio_button :adjustment, 0 %> そのまま
          <%= f.radio_button :adjustment, -1 %> 少し弱く
          <%= f.radio_button :adjustment, -2 %> 弱く
        </div>
        <a class="btn-next my-5" href="#q_04">Next</a>
      </div>

      <!-- 質問4 -->
      <div id="q_04" style="display: none;">
        <div class="offset-sm-2 col-sm-8 mt-5 mb-4">
          <h3>Q. どこを特に鍛えたいですか？ (4/5)</h3>
        </div>
        <div class="offset-sm-2 col-sm-8 mb-2">
          <%= f.radio_button :focus, '肩', {checked: true} %> 肩
          <%= f.radio_button :focus, '胸' %> 胸
          <%= f.radio_button :focus, '腕' %> 腕
          <%= f.radio_button :focus, '背中' %> 背中
          <%= f.radio_button :focus, '腹' %> 腹
          <%= f.radio_button :focus, '脚' %> 脚
        </div>
        <a class="btn-next my-5" href="#q_05">Next</a>
      </div>

      <!-- 質問5 -->
      <div id="q_05" style="display: none;">
        <div class="offset-sm-2 col-sm-8 mt-5 mb-4">
          <h3>Q. 何分ぐらいトレーニングしますか？ (5/5)</h3>
        </div>
        <div class="offset-sm-2 col-sm-8 mb-2">
          <%= f.select :allowed_time, [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60], class: "form-select" %> 分
        </div>
        <%= f.submit 'Start!', class: 'btn btn-make my-3' %>
      </div>
    </div>

  <% end %>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

app/views/users/show.html.erb
<div class="text-center my-5">
  <h1>SETTING</h1>
</div>

<div class="form-group mt-3 mb-5">
  <p>メールアドレス</p>
  <p><b><%= @user.email %></b></p>
</div>
<div class="form-group my-5">
  <p>負荷レベル</p>
  <h4 class="d-inline"><%= @level %></h4> / 100
</div>